### ISSUE TITLE
Support delete statement

### ISSUE THREAD

**Issue by pierluc-codes** [kyle-ilantzis/pl-sql-client#10]

**Comment by kyle-ilantzis** [comment]
Support delete et supporte update, c'est la meme chose je pense.

http://docs.oracle.com/javase/7/docs/api/java/sql/Statement.html

executeQuery retourne un ResultSet

et

executeUpdate retourne un int. Il est bon pour des INSERT,UPDATE,DELETE et autre chose comme CREATE TABLE

Est ce que anydb est comme sa?
