### ISSUE TITLE
Support app opened more than once

### ISSUE THREAD

**Issue by kyle-ilantzis** [kyle-ilantzis/pl-sql-client#15]
If the app is opened twice then the last app the be interacted with will most likely write to the config file leaving the other instance in an invalid state.

Make the app watch the config file.
Or when the window receives focus reload the config file.

**Comment by pierluc-codes** [comment]
Watch config is done. Just integrate the callback with the ui :) See pull request #17

**Comment by kyle-ilantzis** [comment]
The app watches the config file. But now I am wondering if we can open more than 1 window of node-webkit.

When developping, nw only allows 1 instance open.

How will the packaged version work? https://github.com/kyle-ilantzis/pl-sql-client/issues/11

**Comment by pierluc-codes** [comment]
It seems to have a problem with the history and multiple isntance.

**Comment by kyle-ilantzis** [comment]
this finishes the issues https://github.com/kyle-ilantzis/pl-sql-client/pull/32
