### ISSUE TITLE
Handle empty query

### ISSUE THREAD

**Issue by pierluc-codes** [kyle-ilantzis/pl-sql-client#19]
By displaying a beautiful error message.

**Comment by pierluc-codes** [comment]
See pull request #22

**Comment by kyle-ilantzis** [comment]
want  multiquery.ERROR_EMPTY_QUERY and multiquery.ERROR_NO_DB_SPECIFIED "constants"

**Comment by pierluc-codes** [comment]
https://github.com/kyle-ilantzis/pl-sql-client/commit/71ad377734613a9e3d8cc2cc8ae33789f6788466
