### ISSUE TITLE
When window is resized dimensions must be remembered

### ISSUE THREAD

**Issue by kyle-ilantzis** [kyle-ilantzis/pl-sql-client#30]
Remember dimensions so that when the app is opened again the window will be the last size and position the user had.

Otherwise the user will hate having to change the window size all the time and will not use the app

**Comment by pierluc-codes** [comment]
probably position x and y too.

it there a setting for maximized too?

**Comment by kyle-ilantzis** [comment]
Je pense pas que maximized est important, 

juste si tu change que monitor de sa va etre bizarre mais sa se fait pas souvent

**Comment by pierluc-codes** [comment]
api reference: https://github.com/nwjs/nw.js/wiki/window

**Comment by kyle-ilantzis** [comment]
There is a bug because of the new Watcher.js

If there is an error when the SettingsStore loads then its update function is not called, which means it does not notify listeners.

This makes the Window not setup its window resize listeners.

To fix the Watcher must accept a default value and on error call update with the default value.
