### ISSUE TITLE
refactor for unit tests

### ISSUE THREAD

**Issue by kyle-ilantzis** [kyle-ilantzis/pl-sql-client#33]
All things are global sinletons. Turn them to things that can be instantiated. Use dependency injection.

Then we could write unit tests after that.

**Comment by pierluc-codes** [comment]
Dependency injection is not necessary in javascript. you can runtime patch.

http://stackoverflow.com/questions/9250851/do-i-need-dependency-injection-in-nodejs-or-how-to-deal-with

**Comment by kyle-ilantzis** [comment]
Okay, no dependency injection.
