### ISSUE TITLE
The readme

### ISSUE THREAD

**Issue by kyle-ilantzis** [kyle-ilantzis/pl-sql-client#36]
The readme is to sparse. When we are done V0 we must revisit the readme

**Comment by pierluc-codes** [comment]
What content would you like to see?

**Comment by kyle-ilantzis** [comment]
I would like to see, in this order:
- A more descriptive introduction. Right now it is just one sentence that means nothing to new comers.
- A screen shot in the introduction. Ideally of the application's main page with nice query performed. Not a query with herp derp data.
- A download section. Download for windows here,  download for mac here, etc...
- Building from source. Small yet descriptive enough steps on how to build from source.
- Features. For each feature provide a screenshot or set of screen shots. Describe what the feature does and how to use it. Ex: Adding databases, Querying, History remembering, and the misc. theme option.
- License, remains the same.
